- name: apt update
  hosts: all
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        state: present
- name: Install Datadog Agent on servers in AWS
  hosts: tag_datadog_yes
  become: yes
  user: ubuntu
  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_api_key: YOUR_API_KEY
    datadog_config:
      logs_enabled: true
      process_config:
        enabled: "true"